
import React from 'react';
import { LoadingSpinner, ImageIcon } from './icons';

interface ImageDisplayProps {
  image: string | null;
  isLoading: boolean;
  error: string | null;
}

export const ImageDisplay: React.FC<ImageDisplayProps> = ({ image, isLoading, error }) => {
  return (
    <div className="w-full flex-grow bg-gray-800/50 border-2 border-dashed border-gray-700 rounded-lg flex items-center justify-center p-4 min-h-[400px]">
      {isLoading && (
        <div className="text-center text-gray-400">
          <LoadingSpinner />
          <p className="mt-4 text-lg animate-pulse">Generating your masterpiece...</p>
        </div>
      )}
      {error && (
        <div className="text-center text-red-400 p-4 bg-red-900/20 rounded-lg">
          <h3 className="font-bold text-lg">An Error Occurred</h3>
          <p>{error}</p>
        </div>
      )}
      {!isLoading && !error && image && (
        <img
          src={image}
          alt="Generated by AI"
          className="max-w-full max-h-full object-contain rounded-md shadow-2xl animate-fade-in"
          style={{ animation: 'fadeIn 0.5s ease-in-out' }}
        />
      )}
      {!isLoading && !error && !image && (
        <div className="text-center text-gray-500">
            <ImageIcon />
            <p className="mt-4 text-lg">Your generated image will appear here</p>
        </div>
      )}
      <style>{`
        @keyframes fadeIn {
          from { opacity: 0; transform: scale(0.95); }
          to { opacity: 1; transform: scale(1); }
        }
        .animate-fade-in {
          animation: fadeIn 0.5s ease-in-out;
        }
      `}</style>
    </div>
  );
};
